### ISSUE TITLE
ability to plot ping loss events

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#10]
_From @arlake228 on March 14, 2015 12:40_

Original [issue 1006](https://code.google.com/p/perfsonar-ps/issues/detail?id=1006) created by arlake228 on 2014-10-22T16:58:21.000Z:

The esmond MA is capturing ping loss, but currently there is no option to plot this.

This is useful for paths where owping is blocked.

_Copied from original issue: perfsonar/project#1004_

**Comment by apertome** [comment]
This was introduced in 4.0 RC1, closing
