### ISSUE TITLE
Ping latency data not showing for 1-day and 3-day views

### ISSUE THREAD

**Issue by apertome** [perfsonar/graphs#102]
Reported on the user list:

> We have ping tests scheduled between our nodes and noticed that the latency graphs do not show the results when selecting the 1-day and 3-day views.  1-week and longer views work fine.   The owamp latency results do not have any issues.    There are also issues on our perfsonar 3.5 boxes.  The 3-day graph view only shows the first 24 hours of ping latency, and then cuts out.

**Comment by apertome** [comment]
I've got a potential fix, need to test it some more

**Comment by apertome** [comment]
There may still be an issue when using base data (12hr selected)

**Comment by apertome** [comment]
After taking a closer look, it appears that the histogram-rtt data type is missing these statistics summary windows:
0
300

I have some code in a branch that tries to fall back more gracefully, but really the better solution here is to just create those summaries in Esmond.

**Comment by arlake228** [comment]
I added a histogram-rtt with summary 0 to the default list. This will make it into 4.0.1. Adding summary window of 300 doesn't probably make sense though since ping runs every 10 minutes by default. You probably just want to use summary 0 in that case. It is not like OWAMP that runs constantly.

**Comment by apertome** [comment]
Just merged the fix for this that accounts for there not being a summary window of 300. Should be done now.
