### ISSUE TITLE
graphData.cgi?action=has_traceroute_data seems to have an invalid URL

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#107]
On ps-dashboard.es.net, the graphs throw a javascript error in the console when trying to find traceroute data. Example is:

http://ps-dashboard.es.net/perfsonar-graphs/cgi-bin/graphData.cgi?action=has_traceroute_data&url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive,http://albq-pt1.es.net:8085/esmond/perfsonar/archive,http://albq-pt1.es.net:8085/esmond/perfsonar/archive,http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.6&dest=198.124.238.122

It looks like maybe its confused by the comma-separated URL. In fact, I am not quite sure why it has a comma-separated URL since its a repeat of the same URL. My guess is it has to do with the fact the graph in question is displaying multiple src/dst pairs since we run throughput and latency tests on separate interfaces. For reference, the graph that generates the URL above is at:

http://ps-dashboard.es.net/perfsonar-graphs/?url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.6&dest=198.124.238.122&url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.6&dest=198.124.238.138&url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.218&dest=198.124.238.122&url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.218&dest=198.124.238.138&

**Comment by vvidic** [comment]
Tried to check this but could not get http://ps-dashboard.es.net/perfsonar-graphs/ to generate that broken url :)

**Comment by arlake228** [comment]
Just clicked the URL again and it still does it. If you are going to the graph, i see a couple 500 errors to similar URLs in my javascript console. I'm in Safari on mac, not sure that it matters though.

**Comment by vvidic** [comment]
On Fri, Sep 01, 2017 at 08:52:45AM -0700, Andrew R. Lake wrote:
> Just clicked the URL again and it still does it. If you are going to
> the graph, i see a couple 500 errors to similar URLs in my javascript
> console. I'm in Safari on mac, not sure that it matters though.

Ok, I see 4 requests failing with 500 Internal Server Error when loading
the page.  Will try to debug it...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
The problem seems to be that ``ma_url`` is an array with 4 elements here:

    retrieveTracerouteData: function ( sources, dests, ma_url ) {
         let baseUrl = "cgi-bin/graphData.cgi?action=has_traceroute_data";
         baseUrl += "&url=" + ma_url;

so this generates ``&url=url1,url2,url3,url4``.

Please test [this patch](https://github.com/perfsonar/graphs/commit/17a9abf8832ca3bcd0e4c579682cec37bdc3a565) as I don't have the nodejs required to rebuild this :)

**Comment by apertome** [comment]
I will test this, thanks @vvidic !

**Comment by apertome** [comment]
Tested/merged in PR #110
