### ISSUE TITLE
bundle.js needs to be minified

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#108]
The file /usr/lib/perfsonar/graphs/html/public/bundle.js is currently 5.8MB. It is currently not minified and seems to be the primary hold-up for loading the graphs in a lot of cases. Minifying should in theory reduce the size significantly and speed-up the load time.

**Comment by apertome** [comment]
I went ahead and did this really quickly; the minified file is about 2.4 megs (1/3 the size of the un-minified version). 

Note that there are quite a few dependencies we can drop after we stop supporting EL6, so this can shrink further in the future.
