### ISSUE TITLE
Add a way to auto-scale on zoom with the charts

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#11]
_From @arlake228 on March 14, 2015 12:40_

Original [issue 1008](https://code.google.com/p/perfsonar-ps/issues/detail?id=1008) created by arlake228 on 2014-10-24T17:44:45.000Z:

It would be good to have a way to make the charts auto-scale when you zoom in on a region. i.e. there may be a large spike of packet loss and if we select a region outside it we want it to zoom in.

This could be an optional checkbox, or a default behavior.

_Copied from original issue: perfsonar/project#1006_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1008#c1) originally posted by arlake228 on 2014-11-03T16:36:09.000Z:

This can be done, but the way the charting library works, if we enable this option we lose the ability to manually pad values by different amounts, so we once again run into problems with values overwriting each other, especially if the values are consistently near the max. 

Will review further and see if there are any ways around this.

**Comment by apertome** [comment]
I'd like to see if we can roll this into 3.5.1, but not sure yet how time-consuming it will be.

**Comment by apertome** [comment]
This is a feature in the new React charts we'll be adding in 3.6.
