### ISSUE TITLE
Debian port of graphs is missing jQuery

### ISSUE THREAD

**Issue by tonin** [perfsonar/graphs#114]
Since upgrade to 4.0.2.1, the Debian/Ubuntu packages are missing jQuery:
```
ReferenceError: jQuery is not defined
```

`public/jquery` is not existing.

**Comment by apertome** [comment]
The file path changed for jquery; I updated the RPM spec accordingly, but maybe the .deb packages need the same change?

**Comment by tonin** [comment]
I've now seen that it's the react Makefile that has changed and that the jquery files are not any more in `html/public/` in the git repo but copied there by the react Makefile.  Is there a specific reason for that change?

Do I understand correctly that calling the react Makefile is not really needed and we can just package the jquery files from `react/public/`?

**Comment by apertome** [comment]
If I understand correctly, I think this is done? Can we close it?

**Comment by tonin** [comment]
Yes, this is corrected and published.
