### ISSUE TITLE
Labels for TWAMP measurements

### ISSUE THREAD

**Issue by tonin** [perfsonar/graphs#115]
With the current dev-test-mesh TWAMP measurements we have a somewhat confusing visualisation.  See the picture attached.

I'm not sure how best to solve that and don't know anything about the graphs internals.  But, from the user point of view, the clearer for **1** would probably be to introduce yet a different color for Loss and Latency with TWAMP.  Although this would not scale if we are to support any number of tools.

For **2** the solution could be to just omit **(owamp)** and only mention the tool used.

For **3** we could replace **(owamp)** with **(owd)** or **(one-way delay)** and then the tool in brackets.

I would also suggest that the Latency labels be **Latency OWD** and **Latency RTT** rather than **Latency** and **Latency (ping)**

![twamp-visualisation](https://user-images.githubusercontent.com/484879/41872784-815eae52-78b2-11e8-8356-aff5638bfe72.png)

**Comment by apertome** [comment]
I've made some changes close to what you've suggested; here is a screenshot

![screen shot 2018-07-17 at 4 31 05 pm](https://user-images.githubusercontent.com/6306575/42843803-2134183a-89df-11e8-9204-c17629f9ab65.png)


Live chart at:

https://perfsonar-dev8.grnoc.iu.edu/perfsonar-graphs/?source=140.182.49.164&dest=140.182.49.103&url=https%3A%2F%2Fperfsonar-dev8.grnoc.iu.edu%2Fesmond%2Fperfsonar%2Farchive%2F#start=1531254394&end=1531859194&summaryWindow=3600&timeframe=1w

The rtt overlay looks like this:

![screen shot 2018-07-17 at 4 31 51 pm](https://user-images.githubusercontent.com/6306575/42843813-2a56c048-89df-11e8-8b86-620f1787c579.png)

I think this is cleaner and more consistent than what we had before, but the meaning of "owd" and "rtt" (especially owd) may not be immediately obvious to peoplle.

Let me know what you think.

**Comment by tonin** [comment]
This is looking good to me.  Thank you @apertome !  About the meaning of OWD and RTT, maybe we can add that to this page: http://docs.perfsonar.net/release_candidates/4.1b1/using_graphs.html ?

**Comment by apertome** [comment]
I'm going to merge the changes, and then close this, but if you see anything that needs to change, we can reopen.
