### ISSUE TITLE
display timezone in plots

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#12]
_From @arlake228 on March 14, 2015 12:43_

Original [issue 1017](https://code.google.com/p/perfsonar-ps/issues/detail?id=1017) created by arlake228 on 2014-12-04T18:16:19.000Z:

Request from a user:

When attempting to line up perfSONAR graphs with graphs from other systems (e.g. graphite for ESnet, or MRTG, Cacti, etc. for other systems), it is really useful to be able to give the graphs the same time axis.  It makes visual comparison easy, and makes it easy to describe related events to others (esp. people who may not have an engineering background).

I'd like to request a feature for the ESnet statistics graphs and for the perfSONAR graphs - I'd like the ability to set the time zone for the graph.

The new perfSONAR graphs already allow the user to set the range of data that is plotted - that's excellent.  If I could also set the time zone, it would make it much easier to bring perfSONAR information into other contexts (e.g. match against a load plot).

Is this possible?

_Copied from original issue: perfsonar/project#1015_

**Comment by apertome** [comment]
How can we determine the timezone?

We could use the timezone of the Toolkit node where people are viewing the results, or the timezone of the Esmond server, or something else?

**Comment by apertome** [comment]
This is now displayed, it depends on the local system time.
