### ISSUE TITLE
Graph does not load if one of servers is down

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#13]
_From @arlake228 on March 14, 2015 12:43_

Original [issue 1018](https://code.google.com/p/perfsonar-ps/issues/detail?id=1018) created by arlake228 on 2014-12-08T19:00:52.000Z:

We have a graph that points at multiple MAs. One of the MA hosts is not up and this causes none of the graph to load even though the other MA is up and has data. It appears to be due to an unhandled 'undefined' value:

TypeError: undefined is not an object (evaluating 'ps_data.packet_retransmits_src') graphWidget.js:280

Example graph where cern-272-owamp is down and cern-272-pt1.es.net is up (possible the owamp host will be up in the next couple days, thus it may start working):

http://stats.es.net/serviceTest/graphWidget.cgi?url=http://cern-272-pt1.es.net:8085/esmond/perfsonar/archive&amp;source=198.124.238.6&amp;dest=198.124.238.18&amp;url=http://cern-272-pt1.es.net:8085/esmond/perfsonar/archive&amp;source=198.124.238.6&amp;dest=198.124.252.130&amp;url=http://cern-272-owamp.es.net:8085/esmond/perfsonar/archive&amp;source=198.124.238.46&amp;dest=198.124.238.18&amp;url=http://cern-272-owamp.es.net:8085/esmond/perfsonar/archive&amp;source=198.124.238.46&amp;dest=198.124.252.130&amp;

_Copied from original issue: perfsonar/project#1016_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1018#c1) originally posted by arlake228 on 2015-01-30T18:46:58.000Z:

One comment would be to do something more graceful like print the data you get and a warning that some of the MAs could not be reached

**Comment by arlake228** [comment]
michael, is this fixed already?

**Comment by apertome** [comment]
No, this has not been addressed yet

**Comment by sowmyab** [comment]
Fixed in commit 6bdbec29be3747f5c4f176410f3cc698252227d2

**Comment by apertome** [comment]
I believe this can be closed
