### ISSUE TITLE
Would like to see ping latency in psGraph.cgi listing

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#14]
_From @arlake228 on March 14, 2015 12:44_

Original [issue 1026](https://code.google.com/p/perfsonar-ps/issues/detail?id=1026) created by arlake228 on 2014-12-22T16:21:20.000Z:

<b>What steps will reproduce the problem?</b>

Configure a host with basic ping testing (not owamp), and go to psGraph.cgi front page, i.e. test results listing

<b>What is the expected output? What do you see instead?</b>

The &quot;Latency (ms)&quot; and &quot;Loss (%)&quot; columns of the psGraph.cgi listing are currently shown as &quot;n/a&quot;.

It would be great if they could show the results from the latest ping test - either in the src-dst column, or spanning both columns.

<b>What version of the product are you using? On what operating system?</b>

perfsonar ps toolkit 3.4.1

<b>Please provide any additional information below.</b>

_Copied from original issue: perfsonar/project#1024_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1026#c1) originally posted by arlake228 on 2015-01-27T15:02:52.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
Fixed in 110fa71d48000ac24218bf35b75bda644da07199
