### ISSUE TITLE
Display input-source name in psGraph.cgi

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#15]
_From @arlake228 on March 14, 2015 12:44_

Original [issue 1027](https://code.google.com/p/perfsonar-ps/issues/detail?id=1027) created by arlake228 on 2014-12-22T16:54:41.000Z:

<b>What steps will reproduce the problem?</b>

Create test for a target host (foo.example) using its hostname, but which does not have reverse DNS

<b>What is the expected output? What do you see instead?</b>

What I has hoping to see in the psGraph.cgi listing is:

foo.example (192.0.2.252)

What I actually see is:

192.0.2.252 (192.0.2.252)

<b>What version of the product are you using? On what operating system?</b>

perfsonar PS 3.4.1

<b>Please provide any additional information below.</b>

If I look at the top-level JSON info in esmond:

curl http://x.x.x.x/esmond/perfsonar/archive/?format=json | python -m json.tool

I see:

```
    &quot;input-source&quot;: &quot;foo.example&quot;,
```

so it looks like the information is available. (&quot;input-source&quot; is the name, and &quot;input&quot; is the resolved name).

If I add an entry in /etc/hosts for the remote host then the name is displayed in the psGraph.cgi output, which suggests that it is indeed doing a reverse lookup to get the name.

Suggested approach 1:
- if input-source is an IP literal, do a reverse lookup to find the name
- Display &quot;input-source (input)&quot;
- Ditto for &quot;output-source (output)&quot;

This displays the name configured in the test, in preference to what's in reverse DNS.

Suggested approach 2:
- Do a reverse lookup to find the name
- If this fails, use input-source or output-source instead

This preserves current behavior as closely as possible, and only differs if reverse lookup is unavailable

_Copied from original issue: perfsonar/project#1025_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1027#c1) originally posted by arlake228 on 2015-01-21T18:04:05.000Z:

An example of where this is particularly a problem is where you have imported a mesh configuration from maddash, and you see a result like this:

Source: perfsonar.nsrc.org (2607:8400:2880:4::80df:9d2c)
Destination: 2610:28:42c:a::2

Working out what the destination is requires going through the maddash config and doing forward AAAA lookups on all the names.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1027#c2) originally posted by arlake228 on 2015-01-21T18:11:15.000Z:

Also I think it's confusing if you configured a test to an alias B, but reverse DNS gives that machine's primary hostname A. Maybe it would be good to show both?

e.g.

kc-perf.net.ohio-state.edu (perf.net.ohio-state.edu, 2620:0:1a10:125:92e2:baff:fe68:7c29)

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1027#c3) originally posted by arlake228 on 2015-01-27T15:04:21.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
@arlake228 in the past I was told basically never to use the input-source field; it seems like it might make sense to use it here, although I think there would need to be some way of indicating that the hostname being displayed is the stored value, not the current value in DNS. Any thoughts on this?

**Comment by arlake228** [comment]
If you are using it just for display I think it's fine. Using it to determine a hostname to display when DNS otherwise fails seems reasonable. I mainly wanted to avoid people searching on input-source when they should be using source or always expecting a hostname etc. Another thing to keep in mind is it may be something that looks like a hostname, but might be something that only lives in the local /etc/hosts. Thus you might be displaying that something no one else can use. This might not be common, but you might want to verify it resolves prior to displaying it.

**Comment by apertome** [comment]
That makes sense, although it seems like the request specifically wants to see it even if (especially if?) it doesn't resolve.

**Comment by arlake228** [comment]
As I understand, it wants it displayed if the reverse lookup of source/destination doesn't resolve. The forward lookup of the host you get from input-source/destination should still resolve. Its not uncommon for the forward entry to be correctly entered but not the reverse.

**Comment by apertome** [comment]
Hoping to enlist Lisa's help here

**Comment by bltierney** [comment]
Is this fixed?

**Comment by apertome** [comment]
No, this display has not been changed

**Comment by apertome** [comment]
I would argue this is a bigger change than I think I want to make before 4.0; it's debatable, though.

**Comment by bltierney** [comment]
I think this can wait till after 4.0.
