### ISSUE TITLE
graphWidget.cgi not showing full resolution of data

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#16]
_From @arlake228 on March 14, 2015 12:45_

Original [issue 1032](https://code.google.com/p/perfsonar-ps/issues/detail?id=1032) created by arlake228 on 2014-12-23T10:52:57.000Z:

<b>What steps will reproduce the problem?</b>
1. Configure throughput test, interval 3600, to host X
2. Configure ping test, interval 300, to host X
3. Open the graphs via psGraph.cgi -&gt; graphWidget.cgi, and zoom in over a period of say 6 hours

<b>What is the expected output? What do you see instead?</b>

I was expecting to see data points for ping every 5 minutes, and data points for throughput every hour.

However graphWidget shows ping data points only every hour. You can demonstrate this by moving your mouse along the line. There are straight line segments joining the data points at hourly intervals.

<b>What version of the product are you using? On what operating system?</b>

perfsonar PS 3.4.1

<b>Please provide any additional information below.</b>

Looking at regular_testing.log, the ping data collected every 5 minutes is being written to esmond.

_Copied from original issue: perfsonar/project#1030_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1032#c1) originally posted by arlake228 on 2014-12-24T10:21:10.000Z:

Also: if I configure a VM test environment where throughput and ping tests are both configured to run every 5 minutes, the throughput graph is as expected (one point every 5 minutes), but the ping graph only shows one data point per hour.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1032#c2) originally posted by arlake228 on 2014-12-24T11:04:48.000Z:

I found the issue: it can be worked around by learning how to use the GUI in the way Perfsonar wants you to, which is non-obvious.

In JS/graphWidget.js, a summary_window is set based on the initial time scale. When you start at the default view of "1w" the summary window is set to 3600 seconds, and ping information you see is summarised to this level.

Once you are using the 1w view, it doesn't matter how much you zoom in using the slider at the bottom: it remains summarised at this level.

However if you click on "1d", then summary_window=0 and only each burst of (say) 10 pings is summarised, which is what I wanted. Unfortunately you lose your selected position in the time axis, so you have to click "Previous 1d" a sufficient number of times to get to where you wanted to be.

If you click on "3d" the summarisation is done at the level of 300 seconds.

Confusingly, throughput tests are *not* summarised, and this is what leads to the discrepancy between throughput and ping tests which are apparently configured the same.

Suggestions for improvement:

1. Describe the summarisation process, how it is affected by the zoom level, and how it is applied only on certain types of test, at http://docs.perfsonar.net/using_graphs.html

2. Add an explicit indication in the graph display that summarisation is taking place. eg. in the legend put an asterisk next to each summarised variable if summary_window>0

- - - - - Reverse ping*

* summarised over 3600 seconds

3. When selecting a smaller zoom window (e.g. moving from 1w to 3d or 1d), then take into account the current selected time area to choose the default start and end times.

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1032#c3) originally posted by arlake228 on 2015-01-27T15:05:06.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=1032#c4) originally posted by arlake228 on 2015-01-30T18:56:36.000Z:

The react-charts by ESnet does some of that.

**Comment by arlake228** [comment]
![screen shot 2014-12-23 at 10 51 20](https://cloud.githubusercontent.com/assets/634851/6809998/811641da-d234-11e4-8627-27da34584bb6.png)

**Comment by candlerb** [comment]
(Probably should change the title of this issue to something else, e.g. "Indicate what level of summarisation is taking place")

I have another suggestion which would make this a lot clearer for owamp and ping: when hovering over a data point, show the actual number of packets lost, and the number sent.

For example: suppose just 1 packet is lost. At the moment:

* In the 1d zoom, this shows as "Loss: 0.167%"
* In the 1w zoom, the same event shows as "Loss: 0.003%"

I suggest that the hover shows instead:

* "Loss: 0.167% (1 packet out of 600 sent)"
* "Loss: 0.003% (1 packet out of 36000 sent)"

respectively. This makes it much easier to make a judgement call about the severity of an isolated event, without mental gymnastics.

**Comment by candlerb** [comment]
There is more information in [original issue 1038](https://code.google.com/p/perfsonar-ps/issues/detail?id=1038) which doesn't appear to have migrated to github in its own right.

That issue shows some owamp graphs and how the packet loss % shown varies wildly depending on the zoom level, due to the summarisation process - which I believe remains undocumented, at least it is not mentioned  at <http://docs.perfsonar.net/using_graphs.html>

**Comment by apertome** [comment]
This should be handled better in the new charts we plan to implement in 3.6, but is unlikely to change before then.

**Comment by apertome** [comment]
I created a separate ticket for the suggestion for loss display improvements: #35 .

**Comment by bltierney** [comment]
this should be fixed in the new graphs for 4.0
