### ISSUE TITLE
DNS and HTTP test plots

### ISSUE THREAD

**Issue by tonin** [perfsonar/graphs#160]
We have the DNS and HTTP tests working with pScheduler and data is properly stored in Esmond.  We also have the Nagios check plugins and we can build MaDDash grids for HTTP and DNS dashboards.

What we're missing are the graphs to plot the history of past measurements.  We probably need to discuss if we want to support that natively in the perfsonar-graphs or delegate that to Grafana or Kibana.

**Comment by MarkGolderGeant** [comment]
Feature branch pushed to remote today with code awaiting Review

![Screenshot 2020-06-25 at 14 37 27](https://user-images.githubusercontent.com/61050099/85730259-6d93d580-b6f1-11ea-8a5a-6460a24885da.png)

feature/MNG from origin/4.3.0

**Comment by apertome** [comment]
I've reviewed the functionality and I think it's good!

The only issue I'm aware of is the 1yr view not working -- we should open a new ticket for that issue, and close this one. Thoughts?

**Comment by tonin** [comment]
The one year view issue has been resolved and will be part of the 4.3.2 release.
