### ISSUE TITLE
Custom Range date and time selection not working

### ISSUE THREAD

**Issue by tonin** [perfsonar/graphs#166]
On my 4.3-beta deployments, the **Custom Range** date and time selection feature is not working.  I can choose a date and time in the calendar, but they are not reflected on the Date and Time display line underneath the selection boxes and nothing changed in the graphs when I hit **Submit**.

4.2.4 toolkit and MaDDash are working fine, it is a regression we have at least in the 4.3-beta MaDDash gaphs, but probably also in the toolkit (doesn't have one installed at the moment to be able to confirm).

**Comment by apertome** [comment]
Fixed in Centos, can someone check the Debian side?

**Comment by tonin** [comment]
Working for me on a Debian 9 host.
