### ISSUE TITLE
Suggested graph improvement - don't interpolate over long gaps

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#17]
_From @arlake228 on March 14, 2015 12:46_

Original [issue 1036](https://code.google.com/p/perfsonar-ps/issues/detail?id=1036) created by arlake228 on 2015-01-03T11:00:45.000Z:

<b>What steps will reproduce the problem?</b>
1. Configure some throughput graphs
2. Have a large gap in the data (e.g. stop bwctld at the far end for 12-24 hours, then restart it)

<b>What is the expected output? What do you see instead?</b>

I would expect to see a gap in the line graph for the time period when data is not collected. However, psGraph.cgi draws a straight line between the last data point in the old set and the first in the new. IMO this is misleading.

<b>What version of the product are you using? On what operating system?</b>

perfsonar PS 3.4.1

<b>Please provide any additional information below.</b>

Maybe gaps of more than 2x sampling interval should not be interpolated?

_Copied from original issue: perfsonar/project#1034_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1036#c1) originally posted by arlake228 on 2015-01-03T11:11:43.000Z:

However it could be tricky when there is just a single data point here and there, making it clear where these points exist (another example attached).

An option I can think of is to draw the interpolation line but truncate it so just the two tails are visible, pointing towards each other.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1036#c2) originally posted by arlake228 on 2015-01-27T15:06:23.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1036#c3) originally posted by arlake228 on 2015-01-30T19:01:27.000Z:

We will see what this looks like with failures and re-evaluate.

**Comment by arlake228** [comment]
Adding screenshots from google code:
![screen shot 2015-01-03 at 10 55 18](https://cloud.githubusercontent.com/assets/634851/6810059/cc213b6c-d234-11e4-9a44-33728f850083.png)
![screen shot 2015-01-03 at 11 07 54](https://cloud.githubusercontent.com/assets/634851/6810068/d6b2480a-d234-11e4-9086-3ae5addd6929.png)

**Comment by apertome** [comment]
An interesting request. I have mixed feelings about it.

One of the problems with this is that you end up with gaps between test runs too. There is a suggestion that "Maybe gaps of more than 2x sampling interval should not be interpolated?" Something like that could work but makes implementation more complicated.

Individual points could be drawn differently (with a dot) but this adds further complexity.

Also some people have specifically stated that the interpolation is desirable. I tend to agree that it's misleading in cases like this.

**Comment by bltierney** [comment]
lets revisit this for 4.1 after folks get used to the new plots. I have mixed feelings too.

**Comment by apertome** [comment]
With the new graphs, things are a bit different. We can relatively easily add a way to select whether the graphs interpolate between *tests*. So any time a new test is setup or parameters change on an existing test, it shows up as a new test. Currently it's interpolating between the tests, so you can't tell, but this behavior is not difficult to change, so providing this option seems like the best course of action here.

**Comment by apertome** [comment]
We have an option for this in our new Settings panel, but it doesn't work just yet

**Comment by apertome** [comment]
@bhavesh37 implemented this, but it makes no difference in any of the graphs we've tested it with. So we're not including the feature. This is something people can do with more advanced viz tools in the future
