### ISSUE TITLE
Improvements to the "Errors" display on the charts

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#2]
_From @arlake228 on March 14, 2015 12:53_

Original [issue 1079](https://code.google.com/p/perfsonar-ps/issues/detail?id=1079) created by arlake228 on 2015-02-24T18:29:45.000Z:
1. It would be helpful if on the mouseover of the error dots it displayed who initiated the test to aid in debugging. In terms of the esmond JSON, this is just the measurement-agent field from the metadata. I actually think this would be useful as well, so assuming its not too hard to grab that field out of the metadata and plunk it in there, this is probably worth doing.
2. He also thought the term &quot;Error&quot; might be too ambiguous (i.e. are these error counters from SNMP? testing errors? etc). Maybe something like &quot;Test Failures&quot;, &quot;Failed Measurements&quot; or similar?

_Copied from original issue: perfsonar/project#1077_

**Comment by apertome** [comment]
This may happen when we get the new graphs

**Comment by apertome** [comment]
The new graphs support all of this except the measurement-agent
