### ISSUE TITLE
Ability to select summary window on plots

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#20]
_From @arlake228 on March 14, 2015 12:43_

Original [issue 1022](https://code.google.com/p/perfsonar-ps/issues/detail?id=1022) created by arlake228 on 2014-12-18T19:00:25.000Z:

We received this request:

&quot;It would be nice to be able to specify the sample interval for data plotted on the graph. For example, be able to specify a 5-min average, 30-min average, etc when creating a graph. Right now it seems the sample interval is hard set depending on the time frame you select (the 1week graph seems to be hard set to 1-hour average, 3day graph seems to be hard set to 5-min average, etc).&quot;

_Copied from original issue: perfsonar/project#1020_

**Comment by candlerb** [comment]
Related to #16 

* It becomes more important that the summary interval currently in use should be displayed in the graph legend somewhere, if the summary interval is configurable
* Not all lines on the same graph are summarised (e.g. packet loss results are summarised while throughput results are not), so need to indicate which are/are not.

**Comment by bltierney** [comment]
we should look into this for 4.1

**Comment by apertome** [comment]
For now I think we will display the summary window; doing more sophicticated analysis would be better done with other tools i.e. ELK

**Comment by apertome** [comment]
I saw this being displayed in the new Settings panel, but I don't think it is showing up consistently

**Comment by apertome** [comment]
Anything beyond the functionality we already have will need to be done with ELK
