### ISSUE TITLE
Add support for additional MA metadata parameters

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#21]
This issue captures the graphing aspects of perfsonar/project#1076,

 Add support for the following metadata filters to the GET parameters the graph accepts:
* v4 or v6 only
* measurement-agent
* tool-name
* tcp vs udp (BWCTL only)
* udp speeds (BWCTL udp only)
* any other custom filter if possible

**Comment by apertome** [comment]
Received another request for this functionality.

**Comment by arlake228** [comment]
Fixed in f96265cf13621eb7641b11887ce5a444aa96b8d7
