### ISSUE TITLE
psGraph.cgi does not show hosts if only ping tests are configured

### ISSUE THREAD

**Issue by candlerb** [perfsonar/graphs#23]
[host originally installed with ps-Toolkit 3.4.1 but has auto-updates, so I believe is now 3.4.2]

If you configure **only** a ping test to a host, psGraph.cgi does not show it in the list of available graphs (i.e. when you select "Throughput / Latency Graphs" under "View Test Results"). This is despite the fact that the tests do run and the data is being written to esmond.

However, if you configure **both** throughput and ping tests to the same host, then the host is visible in this list; clicking on it shows both the throughput (blue) and ping (yellow) results on the same graph.

With a ping-only target, the only way I can see to get at the graph is to open a different graph, click "Link to this chart", then manually change the `dest=<x.x.x.x>` parameter in the URL

**Comment by candlerb** [comment]
Further investigation: note that this system has 7 active target hosts, 3 of them ping-only.

I find that <http://localhost/serviceTest/graphData.cgi?action=test_lhost%2Fesmond%2Fperfsonar%2Farchive%2F> *does* return all 7 hosts.

However, <http://localhost/serviceTest/graphData.cgi?action=tests&url=http%3A%2F%2Flocalhost%2Fesmond%2Fperfsonar%2Farchive%2F> includes only 4 hosts, excluding the ping-only ones.

I notice line 540 of graphData.cgi, commented `# TEMP HACK` on the line above, which looks like it is responsible for excluding the ping-only hosts (it ignores everything apart from owamp and throughput tests). Unfortunately, commenting out this line just causes graphData.cgi to hang. So presumably this hack is there for some undocumented reason :-(

At this point I'm stuck as to solving the underlying issue.

**Comment by candlerb** [comment]
I believe this is related to #14

In #14 the host was configured with both throughput and ping tests. The host was displayed in the psGraph.cgi listing, but the latest ping results were not visible in the columnar output.

In this ticket the host was configured only with ping tests, and it did not appear in the psGraph.cgi listing at all.

**Comment by candlerb** [comment]
Workaround I received from [perfsonar-developer](https://lists.internet2.edu/sympa/arc/perfsonar-developer/2015-09/msg00051.html) - this still works with perfsonar 3.5

~~~
--- /opt/perfsonar_ps/serviceTest/cgi-bin/graphData.cgi.orig	2015-09-30 20:01:08.000000000 +0000
+++ /opt/perfsonar_ps/serviceTest/cgi-bin/graphData.cgi	2015-11-06 10:40:39.944728780 +0000
@@ -595,7 +595,7 @@
             my $last_update = $event_type->time_updated();

             # TEMP HACK
-            next unless ($type eq 'throughput' || $type eq 'packet-loss-rate' || $type eq 'histogram-owdelay');
+            next unless ($type eq 'throughput' || $type eq 'packet-loss-rate' || $type eq 'histogram-owdelay' || $type eq 'histogram-rtt');

             $type = 'loss' if ($type eq 'packet-loss-rate');
             $type = 'owdelay' if ($type eq 'histogram-owdelay');
~~~

**Comment by apertome** [comment]
Yes, that's the fix for this. I'll get it added soon. The reason it's checking for specific event types is that, as you saw, it sometimes hangs if it's not restricted to just the relevant event types. It's just more data than the script can handle.

**Comment by apertome** [comment]
Fixed and closed. Should be coming out in 3.5.1 early next year, or sooner if we do a point release between now and then.
