### ISSUE TITLE
Be able to change zoom level while keeping selected time area

### ISSUE THREAD

**Issue by candlerb** [perfsonar/graphs#28]
Suppose you have the 1m view selected. You see a data point of interest, and you want to change zoom level to 1d resolution (so more detail is available).

Unfortunately, clicking 1d will take you to the *latest* time data. So either you have to keep clicking "Previous 1d" over and over again (which is very slow and tedious); or you have to click "link to this chart", go back one day, then manually edit the URL `start_ts=1446638515&end_ts=1446724915` and put in appropriate Unix timestamps - also very tedious.

Suggestion: if you have selected a zoom window in the bottom area under the graph, then when you change the zoom level, that the new graph is centred on or contains the selected zoom window.

**Comment by apertome** [comment]
This is done
