### ISSUE TITLE
Sensible units for packet loss

### ISSUE THREAD

**Issue by candlerb** [perfsonar/graphs#29]
In the toolkit front page table of results, the packet loss appears to be shown in units of "micro-percent" or "milli-percent". Examples: `767 µ`, `10.8 m`

These are not particularly easy units to digest. I would rather see `0.0108%` than `10.8 m`. This is also consistent with the graphs, which always display straight percentages, both on the axes and when hovering over a data point.

Furthermore, these numbers seem pretty meaningless. Micro-percent would be units of 10^-8, but when summarising over one hour, the minimum value seen would be 1/36000 which is 2.8*10^-5.

Arguably parts-per-million (ppm) would be reasonable for very small amounts of packet loss, but even then the resolution would be 28ppm per packet lost over an hour.

Finally: it is not even clear what value is being displayed in this table. Is it the most recent measurement over 1 minute, the most recent measurements averaged over 1 hour, over 24 hours, something else?  Milli-percent and micro-percent don't make any sense for measurements over 1 minute, since the lowest detectable packet loss would be 0.167%

This is related to a suggestion made in #16, which is a packet loss value like 0.167% could also hover to show "1 packet out of 600" or whatever the actual measurement was.

**Comment by apertome** [comment]
Starting in 3.5.1, we're using scientific notation for loss instead. It's still showing a percentage, but in scientific notation. So like 1.26e-6%.

**Comment by candlerb** [comment]
IMO that's worse - sorry :-(

Fractional loss expressed in scientific notation I could live with (i.e. 1e-2 = 1%), if it was used consistently everywhere. It would require a bit of retraining, but it's pretty standard for things like Bit Error Rates. It's also clear that 1.23e-6 means 1.23ppm.

But *percentages* expressed as scientific notation?! Sure, just remember to add two to the exponent all the time. Erm, or is it [subtract 2](http://dilbert.com/strip/1993-03-20)?

If we have to have this, please can you make sure that the cutoff point at which formats are switched is consistent everywhere in the UI. What would be really terrible is showing 0.001% in one place and 1e-3% in another place, and then trying to work out whether they are actually the same thing or different by 1 or more orders of magnitude.

Practically speaking: perfsonar by default sends 10pps and if you zoom out far enough you can get summarisation over 86400 seconds. This means most users are unlikely to see packet loss finer than about 1ppm (1e-6).

As a percentage that's 0.0001% (or 1e-4%). I'd say it's just about OK to stay with regular notation at that point. I think it's easy enough to visually distinguish 0.01%, 0.001%, 0.0001%. More than three zeros and I'd agree that it wouldn't be possible.

I'd also concede that it's bit ungainly if you want three significant figures (e.g. 0.000456%). At this level `4.56ppm` might be better, or `4.56e-6` (which is clearly the same as 4.56ppm). But `4.56e-4%`? I am unconvinced.

**Comment by mfeit-internet2** [comment]
This came up on the dev call yesterday.  I suggested scientific notation but neglected to say that we should express it as a straight fraction of packets sent instead of a percentage.  So that one's on me.  :-)

I favor scientific notation because it's easy to tell at a glance what kind of magnitude you're dealing with, whether the plot is log or linear and, if the exponents are all the same, the approximate differences between points on the chart.

**Comment by apertome** [comment]
Well that is a simple change, so let's drop the %. I debated back and forth and didn't feel strongly about it either way, so thanks for the feedback.

**Comment by apertome** [comment]
OK, I dropped the % so now it's just straight scientific notation.
