### ISSUE TITLE
Ability to plot IPv4 and IPv6 separately on same graph

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#3]
_From @arlake228 on March 14, 2015 12:38_

Original [issue 1002](https://code.google.com/p/perfsonar-ps/issues/detail?id=1002) created by arlake228 on 2014-10-15T14:54:08.000Z:

It was requested that it would be nice to have the option to split IPv4 and IPv6 lines for the same data type. For example have a line for IPv6 throughput and IPv4 throughput so they could be compared. 

_Copied from original issue: perfsonar/project#1000_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1002#c1) originally posted by arlake228 on 2014-10-16T20:40:45.000Z:

The table listing the tests sees ipv4 and ipv6 addresses as completely different hosts, so there's no way to do this on the toolkit level.

We could make the chart allow separate ipv4 and ipv6 host parameters, which maddash could pass. Then we could show those tests separately on the graph. The charts currently don't allow multiple values of the same test type, so it would require some doing to make this work.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1002#c2) originally posted by arlake228 on 2015-01-27T15:27:32.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
We can do this now.
