### ISSUE TITLE
Add possibility to plot TCP or UDP throughput

### ISSUE THREAD

**Issue by tonin** [perfsonar/graphs#30]
Currently, when there are both UDP and TCP throughput measurements in the DB, the charts are plotting both types of measurements in the same line.  It would be nice to have the possibility to distinguish between the two, either through the possibility to plot only one or the other, or by having distinct lines for UDP and TCP measurements.

This is just a matter of having a check box or 2 lines drawn from the GUI, because the charts can already distinguish between the 2 types of measurements by using the correct `protocol=tcp` or `protocol=udp` arg when calling the esmond API.  Ex: https://86.119.26.188/serviceTest/graphWidget.cgi?source=10.8.0.18&dest=10.8.0.1&url=http%3A%2F%2Flocalhost%2Fesmond%2Fperfsonar%2Farchive%2F&protocol=tcp#timeframe=1d

**Comment by apertome** [comment]
The new charts differentiate between TCP/UDP throughput
