### ISSUE TITLE
Path change breaks maddash and other embedded graphs

### ISSUE THREAD

**Issue by apertome** [perfsonar/graphs#31]
The change from /serviceTest/ to /perfsonar-graphs/ broke the maddash for the testbed in that when you click on a cell, it attempts  to show the graph but instead you get a 404 error.

I suggested creating a redirect so /serviceTest/ URLs will be redirected to /perfsonar-graphs/ so this won't break when people upgrade.

**Comment by apertome** [comment]
@arlake228 or I should fix this. Assigning to myself for now.

**Comment by arlake228** [comment]
Don't do a redirect, I'll have the maddash spec fix this. I thought I did
but must have forgot. It does the same for the nagios checks. Running mesg
config again should also fix this

**Comment by apertome** [comment]
assigning @arlake228

**Comment by arlake228** [comment]
This should be fixed in both maddash and the mesh-config now (looks like I forgot it in both). I will wait until to testbed updates to confirm and then close the issue.

**Comment by arlake228** [comment]
looks like it was fixed on testbed.
