### ISSUE TITLE
Improve scheduled tests graph window visibility

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/graphs#37]
Hi,
I'm accessing the WebGUI under Windows10. When opening the bandwidth graph it seems the right side of the border of the graph window is not visible (the black rectangle). The window doesn't scale so there is no way to widen it.
I also don't know if so much white space at the bottom of the graph (it always take the space up to the bottom of the screen) is intentional and necessary.
See attached screenshot.
Szymon
![graphs_no_frame](https://cloud.githubusercontent.com/assets/12281679/15173731/179eec6e-175e-11e6-9a2a-60001774e201.png)

**Comment by apertome** [comment]
The new graphs eliminate this issue
