### ISSUE TITLE
Fix error string formatting in graphs

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/graphs#46]
The current formatting of error string in result graphs is invalid. It makes them almost unable to read. If the string is a bit longer it's out of the graph window or it's at least simply out of the error rectangle because there is no line wrapping. See attachments for examples. It should be somehow better formatted (or made shorter out of the whole error) so that it's readable.
![graph-error-1](https://cloud.githubusercontent.com/assets/12281679/19509835/e7ed4856-95e0-11e6-988c-7f0ce600d878.png)
![graph-error-2](https://cloud.githubusercontent.com/assets/12281679/19509836/e7f24572-95e0-11e6-8d75-525495907f99.png)

**Comment by apertome** [comment]
Szymon, this is related to a shortcoming in chartling library that doesn't allow formatting those better. However the plan is that the entire method of displaying those error messages will change. Leaving this ticket open to track that.

**Comment by szymontrocha** [comment]
ok, changing it to enhancement then rather than bug as I guess it's not an immediate change

**Comment by apertome** [comment]
This has been improved, but I still need to adapt the formatting for pscheduler tests (which now have a different format)

**Comment by apertome** [comment]
I've learned that the format has NOT changed , the odd behavior I was seeing was a result of the archiver not storing the error messages correctly. So, this is done.
