### ISSUE TITLE
Minor: IPv4 and IPv6 address displayed on graph

### ISSUE THREAD

**Issue by igarny** [perfsonar/graphs#50]
Hi Michael,

Having a look at the Dev Test dashboard, where antg-dev.es.net participates, you will notice that the server appears with 2 IP addresses. http://ps-test.ctc.grnoc.iu.edu/maddash-webui/details.cgi?uri=/maddash/grids/Development+Testbed+-+BWCTL+4H+TCP+Test+Between+Testbeds/psps-test2-mgmt.rrze.uni-erlangen.de/antg-dev.es.net/Throughput+Alternate+MA
I find this as a step back from former graphs implementation, where just by looking at the IP addresses I could orient myself at which measurement I am looking. It is quite valuable, when you open multiple graph windows for comparison.
Would it be possible to present the IP address as found in Esmond data and not from a hostname resolution?

Regards,
Iv an

**Comment by apertome** [comment]
The IP addresses are displayed, not clear on what you are asking for here
