### ISSUE TITLE
Add more host details to graph

### ISSUE THREAD

**Issue by apertome** [perfsonar/graphs#52]
add more to host details (everything?)

- [x] OS, version?

- [x] city/state?

- LATER: Link to full LS page under host details? (can't do this right now, no way to link directly to a specific node) can maybe send LS a URI URL parameter?

**Comment by bltierney** [comment]
Here is the full list I think should be included:
OS version, perfsonar version, bundle type
CPU speed, number cores, amount of memory
City, State, Country
is it a VM

**Comment by apertome** [comment]
This is much easier now that we have the LS cache, so going to try to fit it in for 4.0.2.
