### ISSUE TITLE
Graphs: Use a log scale where appropriate

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#6]
_From @arlake228 on March 14, 2015 12:28_

Original [issue 962](https://code.google.com/p/perfsonar-ps/issues/detail?id=962) created by arlake228 on 2014-08-01T15:05:47.000Z:

Use a log scale where appropriate on the plots -- probably on loss and delay.

_Copied from original issue: perfsonar/project#960_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=962#c1) originally posted by arlake228 on 2014-08-21T15:57:44.000Z:

This should be an option, not necessarily the default.

However, this has been deemed low priority. We may or may not try to include it in the 3.4 release.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=962#c2) originally posted by arlake228 on 2014-08-27T15:45:05.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=962#c3) originally posted by arlake228 on 2015-01-27T14:44:54.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
We have an option for this now, though it's not working just yet

**Comment by apertome** [comment]
This is in place
