### ISSUE TITLE
Allow display of additional statistical values (min, median, etc)

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#7]
_From @arlake228 on March 14, 2015 12:29_

Original [issue 963](https://code.google.com/p/perfsonar-ps/issues/detail?id=963) created by arlake228 on 2014-08-01T15:09:09.000Z:

Currently we are displaying the mean on the graphs, but it would be useful to be able to see min/max as well.

Median may also be better than mean. Look into this further.

_Copied from original issue: perfsonar/project#961_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c1) originally posted by arlake228 on 2014-08-01T17:22:43.000Z:

min should be the default for latency

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c2) originally posted by arlake228 on 2014-08-18T14:12:30.000Z:

Min is now the default. Need to add an option for median, per last week's developer meeting

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c3) originally posted by arlake228 on 2014-08-27T14:51:24.000Z:

Issue 960 has been merged into this issue.

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c4) originally posted by arlake228 on 2014-08-27T14:51:58.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#5](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c5) originally posted by arlake228 on 2014-09-08T21:00:09.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#6](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c6) originally posted by arlake228 on 2014-09-24T13:47:45.000Z:

Moving addition of median to a later release

**Comment by arlake228** [comment]
Comment [#7](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c7) originally posted by arlake228 on 2014-12-18T18:41:20.000Z:

We have another request relating to this, from the perfsonar-user list:

Be able to plot other values on the graphs (minimum latency, average
latency, maximum latency, mean deviation, etc) like we used to be able
to do in older versions of the PSToolkit.

**Comment by arlake228** [comment]
Comment [#8](https://code.google.com/p/perfsonar-ps/issues/detail?id=963#c8) originally posted by arlake228 on 2015-01-27T14:45:12.000Z:

&lt;empty&gt;

**Comment by bltierney** [comment]
can this be closed?

**Comment by apertome** [comment]
No, we have better defaults now, but being able to select say min, mean, max etc is something we can't do yet. That'd be for 4.1 at the soonest.
