### ISSUE TITLE
Graphs with multiple source/dest pairs in GET params don't display

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#75]
As title says if you try a graph using multiple source and dest pairs it doesn;t display properly. It looks like the graph tries to display data as you'll see a graph for a split second but then it shows "Error unable to retrieve data". This is a blocker for upgrading the ESnet dashboard since we use separate interfaces for OWAMP and throughput.

Below is one example, but really can look at just about any graph URL on https://ps-dashboard.es.net if need more samples:

Works: https://perfsonar-testbed-ma.grnoc.iu.edu/perfsonar-graphs/?url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.6&dest=198.124.252.141

Works https://perfsonar-testbed-ma.grnoc.iu.edu/perfsonar-graphs/?url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.218&dest=198.124.252.154

Doesn't work: https://perfsonar-testbed-ma.grnoc.iu.edu/perfsonar-graphs/?url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.6&dest=198.124.252.141&url=http://albq-pt1.es.net:8085/esmond/perfsonar/archive&source=198.129.254.218&dest=198.124.252.154

**Comment by apertome** [comment]
This should be fixed; building a new RPM. Adding Andy so he can test once it's deployed.

**Comment by arlake228** [comment]
This seems to be working now. Closing.
