### ISSUE TITLE
Address scaling issues in table listing tests with many tests

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#8]
_From @arlake228 on March 14, 2015 12:31_

Original [issue 972](https://code.google.com/p/perfsonar-ps/issues/detail?id=972) created by arlake228 on 2014-08-28T20:56:04.000Z:

If an MA has many tests defined, the table listing the tests never loads. So, the user can't click and see the graphs.

_Copied from original issue: perfsonar/project#970_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=972#c1) originally posted by arlake228 on 2014-08-28T20:58:21.000Z:

This issue was updated by revision 9f6f9290f20e.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=972#c2) originally posted by arlake228 on 2014-08-28T21:11:19.000Z:

Changed to show a more stripped-down table if there are tests over a certain number (15 source-dest pairs at the moment) with just source and destination. This scales much better, but we're going to have to add pagination at some point as well.

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=972#c3) originally posted by arlake228 on 2014-09-24T13:41:02.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=972#c4) originally posted by arlake228 on 2015-01-27T14:45:28.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#5](https://code.google.com/p/perfsonar-ps/issues/detail?id=972#c5) originally posted by arlake228 on 2015-01-30T18:35:25.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
This is related to toolkit#70 .

**Comment by apertome** [comment]
We have pagination and better scaling of the list in 4.0rc2. Closing
