### ISSUE TITLE
Create some checklist manual tests to check the GUI elements

### ISSUE THREAD

**Issue by apertome** [perfsonar/graphs#83]
- [x] Create some manual checklists to help test GUI elements interactively, in a formal/repeatable way.
- [x] Publish this info somewhere

**Comment by apertome** [comment]
Adding John (@somedatapacket) who will be helping with this, but I don't think he's in the ps org yet.

**Comment by apertome** [comment]
Want to at least have a basic checklist for testing the graphs for 4.0.1. The rest can wait until 4.1.

**Comment by somedatapacket** [comment]
Wrote a draft checklist - in the pS testing google drive folder.

**Comment by arlake228** [comment]
Is this done? If so, close it.

**Comment by apertome** [comment]
Very close, we're making a few revisions and then it will be done.
