### ISSUE TITLE
psGraph.cgi sorts by IP address not hostname

### ISSUE THREAD

**Issue by arlake228** [perfsonar/graphs#9]
_From @arlake228 on March 14, 2015 12:38_

Original [issue 1001](https://code.google.com/p/perfsonar-ps/issues/detail?id=1001) created by arlake228 on 2014-10-15T14:20:46.000Z:

There was a comment that the current psGraph.cgi currently sorts by IP address even though the hostname is featured more prominently. This was found to be confusing and made it harder to find tests. They also noted that they would like more consistency as to what was source and destination.

_Copied from original issue: perfsonar/project#999_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1001#c1) originally posted by arlake228 on 2014-10-16T15:55:12.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1001#c2) originally posted by arlake228 on 2014-10-16T20:43:18.000Z:

Good suggestions, I took ownership and will pursue these ideas.

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1001#c3) originally posted by arlake228 on 2014-10-24T14:20:59.000Z:

This issue was updated by revision 9174d10ec1cf.

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=1001#c4) originally posted by arlake228 on 2014-10-24T14:22:27.000Z:

I improved the sorting of the table to sort by hostname, this makes a lot more sense. Still need to make it more consistent as to what is source and what is destination.

**Comment by arlake228** [comment]
Comment [#5](https://code.google.com/p/perfsonar-ps/issues/detail?id=1001#c5) originally posted by arlake228 on 2014-11-26T19:26:28.000Z:

This issue was updated by revision 9174d10ec1cf.

**Comment by apertome** [comment]
It would be good to at least remember which addresses it has listed as source and remain consistent in how it displays them. 

Better would be to detect the local addresses (we already have code that does this part). Then, anything that is on the local machine should be considered the "source"

**Comment by apertome** [comment]
We have made some improvements here but more coming. Pushing to 3.6.

**Comment by apertome** [comment]
moved to #25 , closing this ticket
