### ISSUE TITLE
Change summary windows on graphs

### ISSUE THREAD

**Issue by apertome** [perfsonar/graphs#93]
@apertome commented on [Thu Jun 15 2017](https://github.com/perfsonar/project/issues/1164)

Request from candlerb to change the summary window for 1 day to 0. He says it was that way in 3.5. I don't remember changing it, but he could be right.

Either way, need to do some testing and make sure it performs well enough, but this seems reasonable to me.

**Comment by arlake228** [comment]
Duplicates #20.

**Comment by apertome** [comment]
I was mistaken, this is not a duplicate of #20. This one is a request to change the summary window for the 1 day view to 0.

**Comment by arlake228** [comment]
@apertome can you add a time estimate?

**Comment by apertome** [comment]
I thought I estimated this, but apparently not. Fixed. This is a minor tweak, the only wrinkle is testing the performance, which should not be too involved.

**Comment by apertome** [comment]
After poking at it a bit, my memory has been refreshed. The issue with setting it to 0 is that then we run up against the Esmond 1500 point limit. We either need to offer a 12h window and then use a summary window of 0, or get around the 1500 point limit.

**Comment by apertome** [comment]
Looks like a day's worth of owamp data is about 2861 data points

**Comment by apertome** [comment]
I've added a 12h option to the dropdown, and the with summary window 0, that ends up being 1435 points back
