### ISSUE TITLE
retransmitions report is misleading ( not cleared ) on subsequent results

### ISSUE THREAD

**Issue by igarny** [perfsonar/graphs#98]
Hi Michael

Check this graph: [esnet-monitor](http://ps-dashboard.es.net/perfsonar-graphs/?url=http://amst-pt1.es.net:8085/esmond/perfsonar/archive&source=62.40.106.139&dest=198.124.238.14&url=http://amst-pt1.es.net:8085/esmond/perfsonar/archive&source=62.40.106.139&dest=198.124.238.162&url=http://amst-pt1.es.net:8085/esmond/perfsonar/archive&source=62.40.106.137&dest=198.124.238.14&url=http://amst-pt1.es.net:8085/esmond/perfsonar/archive&source=62.40.106.137&dest=198.124.238.162&#start=1498029442&end=1498634242&summaryWindow=3600&timeframe=1w)

There you will see how a single case of a retransmition is presented for all measurements, before and after the event, which presumably did not experience retransmitions.

**Comment by apertome** [comment]
Hi Ivan,

Thanks for reporting this -- I've committed a fix, which should start making its way into our builds soon.
